// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqrkxhqcydiycmuncdsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxcmt4aHFjeWRpeWNtdW5jZHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNTE2NjgsImV4cCI6MjA1NTkyNzY2OH0.LGF_UamPZEuNQv8OqqPfznLyu75CD5AIMhtkeMF4M0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);